### ISSUE TITLE
jenkins-master deployment fails in OpenShift because keytool command not found

### ISSUE THREAD

**Issue by georgfedermann** [opendevstack/ods-core#578] opened 2020-05-22 09:26 UTC
**Describe the bug**
jenkins-master deployment fails in OpenShift because keytool command cannot be found

**To Reproduce**
1. Create DeploymentConfig for jenkins-master using tailor
2. Start jenkins-master deployment
3. Open jenkins-master pod log file

**Expected behavior**
jenkins-master gets deployed and is up and running.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack master

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
INFO: found /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
INFO: importing into cacerts
/usr/libexec/s2i/ods-run: line 12: keytool: command not found
```

**Comment by michaelsauter** [comment] 2020-05-22 10:29
Duplicate of #575.

**Closed by michaelsauter** 2020-05-22 10:29 UTC
Labels: bug
