### ISSUE TITLE
make sync-repos not pushing tags

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-core#797] opened 2020-09-04 12:09 UTC
trying to clean install ods3 but forcing using tags instead of branches, I notice that sync-repos target is not pushing tags

**Comment by michaelsauter** [comment] 2020-09-07 06:28
#773 will require some rework of the script, and then this should work. Right now, only branches work. I consider this issue a duplicate of https://github.com/opendevstack/ods-core/issues/577.

**Closed by michaelsauter** 2020-09-07 06:28 UTC
Labels: bug
