### ISSUE TITLE
AMI Bulid for branch 3.x falining due to missing file in fe-ionic qs

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-core#974] opened 2021-04-19 13:23 UTC
**Describe the bug**
AMI Bulid for branch 3.x falining due to missing file in fe-ionic qs build.

This is happening since April 12.

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
Adjust package.json to have the full testESC[0m
ESC[0;32m    amazon-ebs: + sed -i 's|\s*"test": "ng test"|"test": "ng test --code-coverage --reporters=junit --progress=false"|' ./package.jsonESC[0m
ESC[0;32m    amazon-ebs: + sed -i 's|\s*"devDependencies": {|"devDependencies": { "karma-junit-reporter": "^2.0.1",|' ./package.jsonESC[0m
ESC[0;32m    amazon-ebs: + echo 'Fix linting rules to run with generated tests'ESC[0m
ESC[0;32m    amazon-ebs: Fix linting rules to run with generated testsESC[0m
ESC[0;32m    amazon-ebs: + sed -i 's|\s*"rules": {|"rules": { "one-variable-per-declaration": false,|' ./tslint.jsonESC[0m
ESC[0;32m    amazon-ebs: sed: can't read ./tslint.json: No such file or directory
[Pipeline] }ESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] // stageESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] }ESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] // nodeESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] }ESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] // podTemplateESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] End of PipelineESC[0m
ESC[0;32m    amazon-ebs: ERROR: script returned exit code 2ESC[0m
ESC[0;32m    amazon-ebs: Finished: FAILUREESC[0m
ESC[0;32m    amazon-ebs: Provision pipeline run for fe-ionic-test returned:ESC[0m
ESC[0;32m    amazon-ebs: [ESC[0m
ESC[0;32m    amazon-ebs:   {ESC[0m
ESC[0;32m    amazon-ebs:     "stage": "Checkout quickstarter",ESC[0m
ESC[0;32m    amazon-ebs:     "status": "SUCCESS"ESC[0m
ESC[0;32m    amazon-ebs:   },ESC[0m
ESC[0;32m    amazon-ebs:   {ESC[0m
ESC[0;32m    amazon-ebs:     "stage": "Initialize output directory",ESC[0m
ESC[0;32m    amazon-ebs:     "status": "SUCCESS"ESC[0m
ESC[0;32m    amazon-ebs:   },ESC[0m
ESC[0;32m    amazon-ebs:   {ESC[0m
ESC[0;32m    amazon-ebs:     "stage": "update ionic cli",ESC[0m
ESC[0;32m    amazon-ebs:     "status": "SUCCESS"ESC[0m
ESC[0;32m    amazon-ebs:   },ESC[0m
ESC[0;32m    amazon-ebs:   {ESC[0m
ESC[0;32m    amazon-ebs:     "stage": "init ionic project",ESC[0m
ESC[0;32m    amazon-ebs:     "status": "FAILED"ESC[0m
ESC[0;32m    amazon-ebs:   }ESC[0m
ESC[0;32m    amazon-ebs: ]ESC[0m
ESC[0;32m    amazon-ebs:     jenkinsfile_test.go:60: Jenkins stages mismatch for provisioning of fe-ionic-test (-want +got):ESC[0m
ESC[0;32m    amazon-ebs:           strings.Join({ESC[0m
ESC[0;32m    amazon-ebs:                ... // 13 identical linesESC[0m
ESC[0;32m    amazon-ebs:                "  {",ESC[0m
ESC[0;32m    amazon-ebs:                `    "stage": "init ionic project",`,ESC[0m
ESC[0;32m    amazon-ebs:         -      `    "status": "SUCCESS"`,ESC[0m
ESC[0;32m    amazon-ebs:         -      "  },",ESC[0m
ESC[0;32m    amazon-ebs:         -      "  {",ESC[0m
ESC[0;32m    amazon-ebs:         -      `    "stage": "Create OpenShift resources",`,ESC[0m
ESC[0;32m    amazon-ebs:         -      `    "status": "SUCCESS"`,ESC[0m
ESC[0;32m    amazon-ebs:         -      "  },",ESC[0m
ESC[0;32m    amazon-ebs:         -      "  {",ESC[0m
ESC[0;32m    amazon-ebs:         -      `    "stage": "Create Jenkinsfile",`,ESC[0m
ESC[0;32m    amazon-ebs:         -      `    "status": "SUCCESS"`,ESC[0m
ESC[0;32m    amazon-ebs:         -      "  },",ESC[0m
ESC[0;32m    amazon-ebs:         -      "  {",ESC[0m
ESC[0;32m    amazon-ebs:         -      `    "stage": "Create sonar-project.properties",`,ESC[0m
ESC[0;32m    amazon-ebs:         -      `    "status": "SUCCESS"`,ESC[0m
ESC[0;32m    amazon-ebs:         -      "  },",ESC[0m
ESC[0;32m    amazon-ebs:         -      "  {",ESC[0m
ESC[0;32m    amazon-ebs:         -      `    "stage": "Push to remote",`,ESC[0m
ESC[0;32m    amazon-ebs:         -      `    "status": "SUCCESS"`,ESC[0m
ESC[0;32m    amazon-ebs:         +      `    "status": "FAILED"`,ESC[0m
ESC[0;32m    amazon-ebs:                "  }",ESC[0m
ESC[0;32m    amazon-ebs:                "]",ESC[0m
ESC[0;32m    amazon-ebs:                "",ESC[0m
ESC[0;32m    amazon-ebs:           }, "\n")ESC[0m
0;32m    amazon-ebs: --- FAIL: TestFeIonic (116.98s)ESC[0m
ESC[0;32m    amazon-ebs: FAILESC[0m
ESC[0;32m    amazon-ebs: FAIL   github.com/opendevstack/ods-quickstarters/tests/fe-ionic        116.990sESC[
```

**Comment by stitakis** [comment] 2021-04-19 13:23
@s2oBCN fyi

**Comment by clemensutschig** [comment] 2021-04-19 13:26
dupe of opendevstack/ods-quickstarters#573

**Closed by clemensutschig** 2021-04-19 13:26 UTC
Labels: bug
