### ISSUE TITLE
Failure when creating a PVC with name “prov-history” because there is already one

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-core#905] opened 2020-11-27 14:34 UTC
**Describe the bug**
When installing ODS 3.1 from ODS 3.0 (minor upgrade) in one of our non-regulated clusters, the `make install-provisioning-app` tries to create a new PVC for the Provisioning Application, even if it's _already_ one.

**To Reproduce**
1. Go to `ods-core`
2. Run `make install-provisioning-app` 
3. See the screenshot below

**Expected behavior**
Given that the pvc/prov-history already exists in the cluster under the same name, it fails when it tries to create it again (Tailor doesn’t seem to detect that there is already a PVC with the same name). I'd expect Tailor to detect if there's already an existing pvc with the same name and if it's the case, then try to update it instead of creating it.

**Screenshots**
![image](https://user-images.githubusercontent.com/15997951/100459184-518fc800-30c5-11eb-9976-8edaaf095986.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.1.0

**Additional context**
The workaround to get this command passed is to skip the PVC resource by adding it to the excluded list in the Makefile as shown below. This way, Tailor will not try to create it.

```bash
## Update OpenShift resources related to the Provisioning App service.
apply-provisioning-app-deploy:
	cd ods-provisioning-app/ocp-config && tailor apply --namespace $(ODS_NAMESPACE) --exclude is,bc,pvc <---- excluded pvc
```

_Note: Interestingly enough, the existing pvc/prov-history in the cluster does not contain any label so that could be the reason why Tailor couldn't identify it in the first place._

**Comment by michaelsauter** [comment] 2020-11-30 07:22
@felipecruz91 The missing label is the issue. Tailor filters all resources which do not have the specified label, which means the PVC is listed as "to be created". That said, Tailor uses `oc apply` under the hood, which works against existing resources, so in the end, no resource is created - the existing resource is updated. In your specific case, the update fails because you change the storage class and provide a lower disk size.

I'm going to close this issue as it is not a bug. It looks like the PVC was manually created?

**Closed by michaelsauter** 2020-11-30 07:22 UTC
Labels: bug
